---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.1.0
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.17.0
  hooks:
    - id: yamllint

# vim: et:sw=2:syntax=yaml:ts=2:
