---
language: python
python:
- "2.7"
- "3.7"
env:
  - ANSIBLE_VERSION="2.5.*"
  - ANSIBLE_VERSION="2.6.*"
  - ANSIBLE_VERSION="2.7.*"
  - ANSIBLE_VERSION="2.8.*"

dist: bionic
addons:
  apt:
    packages:
    - python-pip
    - openssh-server

install:
  # Install ansible
  - pip install "ansible==${ANSIBLE_VERSION}" ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhost_key_checking=false' >ansible.cfg
  - ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa -b 1024
  - cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys

script:
  - ansible-lint tests/*.yml
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
